"""
Static property database with 200+ realistic properties across 10 US cities.
Data is intentionally realistic: prices, neighborhoods, and attributes reflect
actual market conditions as of early 2025.
"""

from typing import List, Dict, Optional
from src.models import Property, PropertyType, ListingStatus, PriceHistory, PriceEvent

PROPERTIES: List[Dict] = [
    # ─────────────────────────── AUSTIN, TX ───────────────────────────
    {
        "id": "atx-001",
        "address": "2847 Barton Hills Dr",
        "city": "Austin",
        "state": "TX",
        "zip_code": "78704",
        "price": 875000,
        "bedrooms": 4,
        "bathrooms": 3.0,
        "sqft": 2640,
        "lot_size_sqft": 8200,
        "year_built": 2018,
        "property_type": "single_family",
        "status": "active",
        "days_on_market": 12,
        "description": "Stunning modern home in coveted Barton Hills. Open floor plan with chef's kitchen, quartz countertops, and stainless appliances. Primary suite with spa bath. Private backyard with deck. Walk to Barton Springs Pool.",
        "features": ["hardwood floors", "quartz countertops", "stainless appliances", "deck", "smart home", "energy star"],
        "garage_spaces": 2,
        "has_pool": False,
        "hoa_monthly": None,
        "taxes_annual": 18200,
        "latitude": 30.2441,
        "longitude": -97.7717,
        "photos_count": 34,
        "listing_agent": "Sarah Mitchell",
        "mls_number": "TX-8847291",
    },
    {
        "id": "atx-002",
        "address": "4512 Speedway Ave #305",
        "city": "Austin",
        "state": "TX",
        "zip_code": "78751",
        "price": 425000,
        "bedrooms": 2,
        "bathrooms": 2.0,
        "sqft": 1150,
        "lot_size_sqft": None,
        "year_built": 2021,
        "property_type": "condo",
        "status": "active",
        "days_on_market": 8,
        "description": "Upscale condo in vibrant Hyde Park. Floor-to-ceiling windows with city views. Modern kitchen with waterfall island. Building amenities include rooftop pool, gym, and concierge.",
        "features": ["city views", "rooftop pool", "gym", "concierge", "waterfall island", "in-unit laundry"],
        "garage_spaces": 1,
        "has_pool": True,
        "hoa_monthly": 385,
        "taxes_annual": 8900,
        "latitude": 30.3075,
        "longitude": -97.7301,
        "photos_count": 28,
        "listing_agent": "Marcus Lee",
        "mls_number": "TX-8831045",
    },
    {
        "id": "atx-003",
        "address": "1923 Enfield Rd",
        "city": "Austin",
        "state": "TX",
        "zip_code": "78703",
        "price": 1450000,
        "bedrooms": 5,
        "bathrooms": 4.5,
        "sqft": 4100,
        "lot_size_sqft": 12400,
        "year_built": 2015,
        "property_type": "single_family",
        "status": "active",
        "days_on_market": 22,
        "description": "Luxury estate in prestigious Tarrytown. Designer finishes throughout. Gourmet kitchen with Wolf and Sub-Zero appliances. Home office, wine cellar, and resort-style backyard with pool and outdoor kitchen.",
        "features": ["wolf appliances", "sub-zero refrigerator", "wine cellar", "home office", "outdoor kitchen", "smart irrigation"],
        "garage_spaces": 3,
        "has_pool": True,
        "hoa_monthly": None,
        "taxes_annual": 30100,
        "latitude": 30.2875,
        "longitude": -97.7601,
        "photos_count": 52,
        "listing_agent": "Jennifer Rawls",
        "mls_number": "TX-8802341",
    },
    {
        "id": "atx-004",
        "address": "7834 Burnet Rd #112",
        "city": "Austin",
        "state": "TX",
        "zip_code": "78757",
        "price": 319000,
        "bedrooms": 1,
        "bathrooms": 1.0,
        "sqft": 780,
        "lot_size_sqft": None,
        "year_built": 2019,
        "property_type": "condo",
        "status": "active",
        "days_on_market": 5,
        "description": "Modern ground-floor condo in North Loop. Open concept living, quartz countertops, and private patio. Building features courtyard, coworking lounge, and bike storage. Walkable to top restaurants.",
        "features": ["private patio", "quartz countertops", "coworking lounge", "bike storage", "pet friendly"],
        "garage_spaces": 1,
        "has_pool": False,
        "hoa_monthly": 275,
        "taxes_annual": 6600,
        "latitude": 30.3321,
        "longitude": -97.7213,
        "photos_count": 18,
        "listing_agent": "Derek Yuen",
        "mls_number": "TX-8859102",
    },
    {
        "id": "atx-005",
        "address": "3301 Pecan Springs Rd",
        "city": "Austin",
        "state": "TX",
        "zip_code": "78723",
        "price": 545000,
        "bedrooms": 3,
        "bathrooms": 2.5,
        "sqft": 1980,
        "lot_size_sqft": 6800,
        "year_built": 2020,
        "property_type": "townhouse",
        "status": "active",
        "days_on_market": 14,
        "description": "End-unit townhome with attached 2-car garage. Rooftop terrace with greenbelt views. Open concept main floor with gas range and large island. Walking distance to Mueller Lake Park.",
        "features": ["rooftop terrace", "greenbelt views", "gas range", "attached garage", "energy star certified"],
        "garage_spaces": 2,
        "has_pool": False,
        "hoa_monthly": 195,
        "taxes_annual": 11300,
        "latitude": 30.2998,
        "longitude": -97.7000,
        "photos_count": 24,
        "listing_agent": "Amanda Torres",
        "mls_number": "TX-8871230",
    },
    {
        "id": "atx-006",
        "address": "908 Oltorf St",
        "city": "Austin",
        "state": "TX",
        "zip_code": "78704",
        "price": 698000,
        "bedrooms": 3,
        "bathrooms": 2.0,
        "sqft": 1820,
        "lot_size_sqft": 5600,
        "year_built": 1965,
        "property_type": "single_family",
        "status": "pending",
        "days_on_market": 4,
        "description": "Beautifully renovated mid-century modern home in South Congress corridor. Original hardwoods preserved, new kitchen with custom cabinetry, new plumbing and electrical. Large fenced yard with mature oaks.",
        "features": ["original hardwoods", "custom cabinetry", "renovated kitchen", "mature oaks", "fenced yard"],
        "garage_spaces": 1,
        "has_pool": False,
        "hoa_monthly": None,
        "taxes_annual": 14500,
        "latitude": 30.2339,
        "longitude": -97.7598,
        "photos_count": 30,
        "listing_agent": "Tom Nguyen",
        "mls_number": "TX-8863445",
    },
    # ─────────────────────────── DENVER, CO ───────────────────────────
    {
        "id": "den-001",
        "address": "1847 Larimer St #401",
        "city": "Denver",
        "state": "CO",
        "zip_code": "80202",
        "price": 589000,
        "bedrooms": 2,
        "bathrooms": 2.0,
        "sqft": 1340,
        "lot_size_sqft": None,
        "year_built": 2017,
        "property_type": "condo",
        "status": "active",
        "days_on_market": 18,
        "description": "Sophisticated LoDo loft with exposed brick and ductwork. Chef's kitchen with gas range, slab marble counters. Two private balconies with mountain views. Steps to Union Station and Denver's best restaurants.",
        "features": ["exposed brick", "mountain views", "two balconies", "marble counters", "gas range", "secure parking"],
        "garage_spaces": 1,
        "has_pool": False,
        "hoa_monthly": 510,
        "taxes_annual": 5200,
        "latitude": 39.7528,
        "longitude": -104.9982,
        "photos_count": 31,
        "listing_agent": "Ryan Kowalski",
        "mls_number": "CO-4421089",
    },
    {
        "id": "den-002",
        "address": "4218 W 33rd Ave",
        "city": "Denver",
        "state": "CO",
        "zip_code": "80212",
        "price": 775000,
        "bedrooms": 4,
        "bathrooms": 3.0,
        "sqft": 2380,
        "lot_size_sqft": 6600,
        "year_built": 2016,
        "property_type": "single_family",
        "status": "active",
        "days_on_market": 9,
        "description": "Craftsman-style home on tree-lined Berkeley street. Open main floor with gas fireplace, custom built-ins, and gourmet kitchen. Finished basement with wet bar. Covered front porch, private backyard.",
        "features": ["gas fireplace", "custom built-ins", "finished basement", "wet bar", "covered porch", "sprinkler system"],
        "garage_spaces": 2,
        "has_pool": False,
        "hoa_monthly": None,
        "taxes_annual": 4800,
        "latitude": 39.7601,
        "longitude": -105.0412,
        "photos_count": 38,
        "listing_agent": "Lisa Chambers",
        "mls_number": "CO-4418753",
    },
    {
        "id": "den-003",
        "address": "2901 Blake St",
        "city": "Denver",
        "state": "CO",
        "zip_code": "80205",
        "price": 420000,
        "bedrooms": 2,
        "bathrooms": 1.5,
        "sqft": 1080,
        "lot_size_sqft": None,
        "year_built": 2020,
        "property_type": "townhouse",
        "status": "active",
        "days_on_market": 21,
        "description": "Modern townhome in RiNo Art District. Rooftop deck with mountain and city views. Ground floor flex space perfect for home office or studio. Minutes from trendy bars, galleries, and dining.",
        "features": ["rooftop deck", "mountain views", "flex space", "modern finishes", "private entrance"],
        "garage_spaces": 1,
        "has_pool": False,
        "hoa_monthly": 145,
        "taxes_annual": 3700,
        "latitude": 39.7648,
        "longitude": -104.9789,
        "photos_count": 22,
        "listing_agent": "Heather Diaz",
        "mls_number": "CO-4432018",
    },
    {
        "id": "den-004",
        "address": "5540 Montview Blvd",
        "city": "Denver",
        "state": "CO",
        "zip_code": "80207",
        "price": 950000,
        "bedrooms": 5,
        "bathrooms": 4.0,
        "sqft": 3600,
        "lot_size_sqft": 10200,
        "year_built": 1928,
        "property_type": "single_family",
        "status": "active",
        "days_on_market": 33,
        "description": "Grand Colonial Revival on prestigious Montview Boulevard with panoramic mountain views. Completely renovated while preserving original character: coffered ceilings, arched doorways, original oak floors. Modern kitchen and baths.",
        "features": ["coffered ceilings", "arched doorways", "original oak floors", "mountain views", "renovated kitchen", "formal dining"],
        "garage_spaces": 2,
        "has_pool": False,
        "hoa_monthly": None,
        "taxes_annual": 6100,
        "latitude": 39.7501,
        "longitude": -104.9232,
        "photos_count": 45,
        "listing_agent": "Craig Benson",
        "mls_number": "CO-4401234",
    },
    {
        "id": "den-005",
        "address": "1122 Sherman St #8B",
        "city": "Denver",
        "state": "CO",
        "zip_code": "80203",
        "price": 349000,
        "bedrooms": 1,
        "bathrooms": 1.0,
        "sqft": 820,
        "lot_size_sqft": None,
        "year_built": 2015,
        "property_type": "condo",
        "status": "active",
        "days_on_market": 11,
        "description": "Stylish Capitol Hill condo with upgraded finishes. Stainless kitchen with gas range, quartz counters. Large windows with city views. Building features gym, bike storage, and secure parking.",
        "features": ["gas range", "quartz counters", "city views", "gym", "bike storage", "rooftop"],
        "garage_spaces": 1,
        "has_pool": False,
        "hoa_monthly": 310,
        "taxes_annual": 2900,
        "latitude": 39.7368,
        "longitude": -104.9843,
        "photos_count": 20,
        "listing_agent": "Mia Santos",
        "mls_number": "CO-4445678",
    },
    # ─────────────────────────── NASHVILLE, TN ───────────────────────────
    {
        "id": "bna-001",
        "address": "3812 Granny White Pike",
        "city": "Nashville",
        "state": "TN",
        "zip_code": "37220",
        "price": 899000,
        "bedrooms": 5,
        "bathrooms": 4.0,
        "sqft": 3800,
        "lot_size_sqft": 14500,
        "year_built": 2019,
        "property_type": "single_family",
        "status": "active",
        "days_on_market": 15,
        "description": "New construction in Oak Hill with exceptional finishes. 10-foot ceilings, wide-plank white oak floors, custom millwork. Chef's kitchen with Thermador appliances. Screened porch and private pool.",
        "features": ["10-foot ceilings", "white oak floors", "thermador appliances", "custom millwork", "screened porch"],
        "garage_spaces": 2,
        "has_pool": True,
        "hoa_monthly": None,
        "taxes_annual": 4200,
        "latitude": 36.0707,
        "longitude": -86.7923,
        "photos_count": 48,
        "listing_agent": "Amy Caldwell",
        "mls_number": "TN-2234891",
    },
    {
        "id": "bna-002",
        "address": "1004 Meridian St",
        "city": "Nashville",
        "state": "TN",
        "zip_code": "37207",
        "price": 485000,
        "bedrooms": 3,
        "bathrooms": 2.5,
        "sqft": 1950,
        "lot_size_sqft": 5200,
        "year_built": 2021,
        "property_type": "single_family",
        "status": "active",
        "days_on_market": 7,
        "description": "Newly built home in East Nashville's Inglewood neighborhood. Modern farmhouse aesthetic with shiplap, open shelving, and matte black fixtures. Front porch and fenced backyard. Top-rated schools nearby.",
        "features": ["shiplap", "open shelving", "matte black fixtures", "front porch", "fenced yard", "smart thermostat"],
        "garage_spaces": 2,
        "has_pool": False,
        "hoa_monthly": None,
        "taxes_annual": 2300,
        "latitude": 36.2001,
        "longitude": -86.7619,
        "photos_count": 29,
        "listing_agent": "Preston Ball",
        "mls_number": "TN-2248732",
    },
    {
        "id": "bna-003",
        "address": "600 12th Ave S #415",
        "city": "Nashville",
        "state": "TN",
        "zip_code": "37203",
        "price": 510000,
        "bedrooms": 2,
        "bathrooms": 2.0,
        "sqft": 1280,
        "lot_size_sqft": None,
        "year_built": 2020,
        "property_type": "condo",
        "status": "active",
        "days_on_market": 20,
        "description": "Luxury condo in 12South within walking distance of Gulch restaurants and boutiques. High ceilings, hardwood floors, and Bosch appliances. Building has saltwater pool, rooftop lounge, and private dog park.",
        "features": ["hardwood floors", "bosch appliances", "saltwater pool", "rooftop lounge", "dog park", "doorman"],
        "garage_spaces": 1,
        "has_pool": True,
        "hoa_monthly": 490,
        "taxes_annual": 4800,
        "latitude": 36.1430,
        "longitude": -86.7961,
        "photos_count": 32,
        "listing_agent": "Carla Hutton",
        "mls_number": "TN-2219045",
    },
    {
        "id": "bna-004",
        "address": "2408 Westwood Ave",
        "city": "Nashville",
        "state": "TN",
        "zip_code": "37212",
        "price": 1250000,
        "bedrooms": 6,
        "bathrooms": 5.5,
        "sqft": 4900,
        "lot_size_sqft": 18000,
        "year_built": 2022,
        "property_type": "single_family",
        "status": "active",
        "days_on_market": 28,
        "description": "Stunning new build in Hillsboro Village. Designer touches throughout including Venetian plaster walls, custom wine room, and theater. Chef's kitchen with La Cornue range. Pool with cabana and outdoor kitchen.",
        "features": ["venetian plaster", "custom wine room", "theater", "la cornue range", "cabana", "outdoor kitchen"],
        "garage_spaces": 3,
        "has_pool": True,
        "hoa_monthly": None,
        "taxes_annual": 5900,
        "latitude": 36.1385,
        "longitude": -86.8098,
        "photos_count": 62,
        "listing_agent": "Brandon Foster",
        "mls_number": "TN-2201567",
    },
    {
        "id": "bna-005",
        "address": "819 Woodland St",
        "city": "Nashville",
        "state": "TN",
        "zip_code": "37206",
        "price": 399000,
        "bedrooms": 2,
        "bathrooms": 1.0,
        "sqft": 1100,
        "lot_size_sqft": 4200,
        "year_built": 1945,
        "property_type": "single_family",
        "status": "active",
        "days_on_market": 3,
        "description": "Charming East Nashville bungalow updated with style. Original hardwoods, new kitchen with subway tile and butcher block counters. Covered porch, raised vegetable beds in backyard. Steps to Five Points.",
        "features": ["original hardwoods", "subway tile", "butcher block counters", "covered porch", "vegetable garden"],
        "garage_spaces": 0,
        "has_pool": False,
        "hoa_monthly": None,
        "taxes_annual": 1900,
        "latitude": 36.1789,
        "longitude": -86.7501,
        "photos_count": 23,
        "listing_agent": "Joy Patterson",
        "mls_number": "TN-2262110",
    },
    # ─────────────────────────── CHARLOTTE, NC ───────────────────────────
    {
        "id": "clt-001",
        "address": "516 Queens Rd W",
        "city": "Charlotte",
        "state": "NC",
        "zip_code": "28207",
        "price": 1100000,
        "bedrooms": 5,
        "bathrooms": 4.5,
        "sqft": 4200,
        "lot_size_sqft": 11800,
        "year_built": 2017,
        "property_type": "single_family",
        "status": "active",
        "days_on_market": 17,
        "description": "Stunning Myers Park home on sought-after Queens Road West. Traditional architecture with modern upgrades. Grand foyer, formal dining, and open kitchen/family room. Primary suite with sitting room. Pool and pool house.",
        "features": ["grand foyer", "formal dining", "pool house", "sitting room", "hardwood floors", "custom closets"],
        "garage_spaces": 2,
        "has_pool": True,
        "hoa_monthly": None,
        "taxes_annual": 8900,
        "latitude": 35.2003,
        "longitude": -80.8443,
        "photos_count": 55,
        "listing_agent": "Catherine Wills",
        "mls_number": "NC-5531209",
    },
    {
        "id": "clt-002",
        "address": "2234 Commonwealth Ave",
        "city": "Charlotte",
        "state": "NC",
        "zip_code": "28205",
        "price": 645000,
        "bedrooms": 4,
        "bathrooms": 3.0,
        "sqft": 2450,
        "lot_size_sqft": 8100,
        "year_built": 2018,
        "property_type": "single_family",
        "status": "active",
        "days_on_market": 10,
        "description": "Modern craftsman in Plaza Midwood. Open floor plan with 10-foot ceilings, gas fireplace, and chef's kitchen. Primary suite with dual walk-ins and spa bath. Large screened porch and private backyard.",
        "features": ["10-foot ceilings", "gas fireplace", "screened porch", "dual walk-ins", "spa bath", "smart home"],
        "garage_spaces": 2,
        "has_pool": False,
        "hoa_monthly": None,
        "taxes_annual": 5200,
        "latitude": 35.2198,
        "longitude": -80.8089,
        "photos_count": 38,
        "listing_agent": "Noah Clarke",
        "mls_number": "NC-5547891",
    },
    {
        "id": "clt-003",
        "address": "400 W 5th St #1802",
        "city": "Charlotte",
        "state": "NC",
        "zip_code": "28202",
        "price": 725000,
        "bedrooms": 2,
        "bathrooms": 2.0,
        "sqft": 1580,
        "lot_size_sqft": None,
        "year_built": 2019,
        "property_type": "condo",
        "status": "active",
        "days_on_market": 24,
        "description": "Corner unit high-rise condo in Uptown Charlotte with panoramic city and Catawba River views. Floor-to-ceiling windows, Calacatta marble kitchen, and wide-plank oak floors. Full-service building with pool, spa, and concierge.",
        "features": ["panoramic views", "floor-to-ceiling windows", "calacatta marble", "oak floors", "full-service", "spa"],
        "garage_spaces": 1,
        "has_pool": True,
        "hoa_monthly": 695,
        "taxes_annual": 6700,
        "latitude": 35.2270,
        "longitude": -80.8461,
        "photos_count": 40,
        "listing_agent": "Diane Walsh",
        "mls_number": "NC-5522034",
    },
    {
        "id": "clt-004",
        "address": "7823 Providence Rd",
        "city": "Charlotte",
        "state": "NC",
        "zip_code": "28226",
        "price": 465000,
        "bedrooms": 3,
        "bathrooms": 2.5,
        "sqft": 2100,
        "lot_size_sqft": 9500,
        "year_built": 2004,
        "property_type": "single_family",
        "status": "active",
        "days_on_market": 6,
        "description": "Well-maintained traditional home in SouthPark area. Hardwood main floor, updated kitchen with granite and stainless. Large bonus room could serve as 4th bedroom. Level backyard with patio.",
        "features": ["hardwood floors", "granite counters", "bonus room", "patio", "cul-de-sac"],
        "garage_spaces": 2,
        "has_pool": False,
        "hoa_monthly": 85,
        "taxes_annual": 3800,
        "latitude": 35.1312,
        "longitude": -80.8219,
        "photos_count": 26,
        "listing_agent": "James Ford",
        "mls_number": "NC-5561345",
    },
    # ─────────────────────────── PHOENIX, AZ ───────────────────────────
    {
        "id": "phx-001",
        "address": "6821 E Lincoln Dr",
        "city": "Phoenix",
        "state": "AZ",
        "zip_code": "85253",
        "price": 1850000,
        "bedrooms": 5,
        "bathrooms": 5.5,
        "sqft": 5800,
        "lot_size_sqft": 28000,
        "year_built": 2020,
        "property_type": "single_family",
        "status": "active",
        "days_on_market": 38,
        "description": "Contemporary estate in guard-gated Paradise Valley with Camelback Mountain views. Negative-edge pool, outdoor entertainment pavilion, and putting green. Opulent primary suite with dual baths. 4-car garage with car lift.",
        "features": ["negative-edge pool", "camelback mountain views", "putting green", "outdoor pavilion", "car lift", "wine room"],
        "garage_spaces": 4,
        "has_pool": True,
        "hoa_monthly": 450,
        "taxes_annual": 12800,
        "latitude": 33.5341,
        "longitude": -111.9424,
        "photos_count": 72,
        "listing_agent": "Monica Stern",
        "mls_number": "AZ-6671245",
    },
    {
        "id": "phx-002",
        "address": "1234 W Encanto Blvd",
        "city": "Phoenix",
        "state": "AZ",
        "zip_code": "85013",
        "price": 520000,
        "bedrooms": 3,
        "bathrooms": 2.0,
        "sqft": 1780,
        "lot_size_sqft": 8200,
        "year_built": 1959,
        "property_type": "single_family",
        "status": "active",
        "days_on_market": 11,
        "description": "Beautifully restored mid-century modern ranch in Encanto-Palmcroft Historic District. Original terrazzo floors, tongue-and-groove ceilings, new roof and HVAC. Desert-landscaped front yard, pool in backyard.",
        "features": ["terrazzo floors", "tongue-and-groove ceiling", "historic district", "new roof", "new hvac", "desert landscaping"],
        "garage_spaces": 2,
        "has_pool": True,
        "hoa_monthly": None,
        "taxes_annual": 3800,
        "latitude": 33.4769,
        "longitude": -112.0826,
        "photos_count": 36,
        "listing_agent": "Raul Espinoza",
        "mls_number": "AZ-6694302",
    },
    {
        "id": "phx-003",
        "address": "8989 N Scottsdale Rd #2210",
        "city": "Phoenix",
        "state": "AZ",
        "zip_code": "85253",
        "price": 389000,
        "bedrooms": 1,
        "bathrooms": 1.5,
        "sqft": 985,
        "lot_size_sqft": None,
        "year_built": 2022,
        "property_type": "condo",
        "status": "active",
        "days_on_market": 14,
        "description": "High-end resort-style condo in North Scottsdale. Chef's kitchen with Sub-Zero refrigerator, gas cooking. Floor-to-ceiling windows. Access to 3 heated pools, lap pool, full spa, and fitness club.",
        "features": ["resort amenities", "heated pools", "full spa", "sub-zero refrigerator", "gas cooking", "fitness club"],
        "garage_spaces": 1,
        "has_pool": True,
        "hoa_monthly": 620,
        "taxes_annual": 2900,
        "latitude": 33.6042,
        "longitude": -111.9198,
        "photos_count": 29,
        "listing_agent": "Diana Frost",
        "mls_number": "AZ-6682011",
    },
    {
        "id": "phx-004",
        "address": "4455 W Thomas Rd",
        "city": "Phoenix",
        "state": "AZ",
        "zip_code": "85031",
        "price": 295000,
        "bedrooms": 3,
        "bathrooms": 2.0,
        "sqft": 1360,
        "lot_size_sqft": 6700,
        "year_built": 1999,
        "property_type": "single_family",
        "status": "active",
        "days_on_market": 4,
        "description": "Move-in ready home with new interior paint, upgraded kitchen, and tiled floors throughout. Covered back patio and easy-maintenance desert landscaping. Close to I-10 and West Valley amenities.",
        "features": ["new paint", "upgraded kitchen", "tiled floors", "covered patio", "desert landscaping"],
        "garage_spaces": 2,
        "has_pool": False,
        "hoa_monthly": None,
        "taxes_annual": 2100,
        "latitude": 33.4813,
        "longitude": -112.1709,
        "photos_count": 20,
        "listing_agent": "Luis Martinez",
        "mls_number": "AZ-6707813",
    },
    {
        "id": "phx-005",
        "address": "2301 N Central Ave #1504",
        "city": "Phoenix",
        "state": "AZ",
        "zip_code": "85004",
        "price": 449000,
        "bedrooms": 2,
        "bathrooms": 2.0,
        "sqft": 1220,
        "lot_size_sqft": None,
        "year_built": 2020,
        "property_type": "condo",
        "status": "active",
        "days_on_market": 19,
        "description": "Sleek midtown Phoenix high-rise condo with sweeping mountain and city views. Integrated smart-home technology, motorized shades, chef's kitchen. Rooftop pool and sky lounge exclusive to residents.",
        "features": ["smart-home technology", "motorized shades", "mountain views", "rooftop pool", "sky lounge", "concierge"],
        "garage_spaces": 1,
        "has_pool": True,
        "hoa_monthly": 445,
        "taxes_annual": 3400,
        "latitude": 33.4748,
        "longitude": -112.0734,
        "photos_count": 33,
        "listing_agent": "Tanya Reeve",
        "mls_number": "AZ-6688456",
    },
    # ─────────────────────────── MIAMI, FL ───────────────────────────
    {
        "id": "mia-001",
        "address": "1100 Brickell Bay Dr #4801",
        "city": "Miami",
        "state": "FL",
        "zip_code": "33131",
        "price": 2100000,
        "bedrooms": 3,
        "bathrooms": 3.5,
        "sqft": 2450,
        "lot_size_sqft": None,
        "year_built": 2021,
        "property_type": "condo",
        "status": "active",
        "days_on_market": 42,
        "description": "Spectacular Brickell penthouse with 270-degree views of Biscayne Bay, Miami Beach, and the skyline. Italian marble throughout, Gaggenau appliances, private pool terrace. Building amenities are unmatched: 3 pools, spa, cinema.",
        "features": ["biscayne bay views", "private pool terrace", "italian marble", "gaggenau appliances", "cinema", "spa"],
        "garage_spaces": 2,
        "has_pool": True,
        "hoa_monthly": 2800,
        "taxes_annual": 25600,
        "latitude": 25.7649,
        "longitude": -80.1886,
        "photos_count": 80,
        "listing_agent": "Isabela Costa",
        "mls_number": "FL-9912847",
    },
    {
        "id": "mia-002",
        "address": "455 NE 30th St",
        "city": "Miami",
        "state": "FL",
        "zip_code": "33137",
        "price": 1350000,
        "bedrooms": 4,
        "bathrooms": 4.0,
        "sqft": 3100,
        "lot_size_sqft": 7400,
        "year_built": 2023,
        "property_type": "single_family",
        "status": "active",
        "days_on_market": 16,
        "description": "New construction in the heart of Edgewater. Soaring 12-foot ceilings, imported stone, and floor-to-ceiling glass. Rooftop terrace with bay glimpses, private heated pool. Corner lot with electric gate. 2 EV chargers.",
        "features": ["12-foot ceilings", "imported stone", "rooftop terrace", "heated pool", "electric gate", "ev chargers"],
        "garage_spaces": 2,
        "has_pool": True,
        "hoa_monthly": None,
        "taxes_annual": 16400,
        "latitude": 25.7994,
        "longitude": -80.1860,
        "photos_count": 58,
        "listing_agent": "Carlos Medina",
        "mls_number": "FL-9928034",
    },
    {
        "id": "mia-003",
        "address": "737 Collins Ave #601",
        "city": "Miami",
        "state": "FL",
        "zip_code": "33139",
        "price": 680000,
        "bedrooms": 1,
        "bathrooms": 1.5,
        "sqft": 900,
        "lot_size_sqft": None,
        "year_built": 2018,
        "property_type": "condo",
        "status": "active",
        "days_on_market": 30,
        "description": "Chic South Beach condo half a block from the ocean. Italian kitchen, spa bath, private balcony. Hotel-style building with beach club access, pool, spa, and valet. Perfect as primary, vacation home, or investment.",
        "features": ["beach club access", "ocean views", "valet", "private balcony", "italian kitchen", "spa"],
        "garage_spaces": 1,
        "has_pool": True,
        "hoa_monthly": 980,
        "taxes_annual": 8100,
        "latitude": 25.7868,
        "longitude": -80.1302,
        "photos_count": 35,
        "listing_agent": "Sofia Reyes",
        "mls_number": "FL-9901823",
    },
    {
        "id": "mia-004",
        "address": "3820 Stewart Ave",
        "city": "Miami",
        "state": "FL",
        "zip_code": "33133",
        "price": 2800000,
        "bedrooms": 5,
        "bathrooms": 5.0,
        "sqft": 5200,
        "lot_size_sqft": 14000,
        "year_built": 2019,
        "property_type": "single_family",
        "status": "active",
        "days_on_market": 55,
        "description": "Magnificent Coconut Grove contemporary with Biscayne Bay canal access and private dock. Zero-edge pool with spa, summer kitchen, and outdoor dining pavilion. Interior design by local award-winning firm. Smart home system.",
        "features": ["canal access", "private dock", "zero-edge pool", "summer kitchen", "outdoor dining pavilion", "award-winning design"],
        "garage_spaces": 3,
        "has_pool": True,
        "hoa_monthly": None,
        "taxes_annual": 34000,
        "latitude": 25.7311,
        "longitude": -80.2406,
        "photos_count": 90,
        "listing_agent": "Patricia Gomez",
        "mls_number": "FL-9878234",
    },
    {
        "id": "mia-005",
        "address": "18555 Collins Ave #2702",
        "city": "Miami",
        "state": "FL",
        "zip_code": "33160",
        "price": 870000,
        "bedrooms": 2,
        "bathrooms": 2.0,
        "sqft": 1400,
        "lot_size_sqft": None,
        "year_built": 2016,
        "property_type": "condo",
        "status": "active",
        "days_on_market": 22,
        "description": "Direct oceanfront condo in Sunny Isles Beach. Wake up to Atlantic Ocean views from every room. Floor-to-ceiling glass, gourmet kitchen, and spa bath. Building has beach attendants, 3 pools, and world-class spa.",
        "features": ["direct oceanfront", "atlantic ocean views", "beach attendants", "3 pools", "world-class spa", "floor-to-ceiling glass"],
        "garage_spaces": 1,
        "has_pool": True,
        "hoa_monthly": 1350,
        "taxes_annual": 10400,
        "latitude": 25.9371,
        "longitude": -80.1228,
        "photos_count": 44,
        "listing_agent": "Michael Blanc",
        "mls_number": "FL-9915670",
    },
    # ─────────────────────────── SEATTLE, WA ───────────────────────────
    {
        "id": "sea-001",
        "address": "2318 E Madison St",
        "city": "Seattle",
        "state": "WA",
        "zip_code": "98112",
        "price": 1150000,
        "bedrooms": 4,
        "bathrooms": 3.0,
        "sqft": 2880,
        "lot_size_sqft": 5200,
        "year_built": 2010,
        "property_type": "single_family",
        "status": "active",
        "days_on_market": 7,
        "description": "Craftsman home in Madison Valley with Puget Sound peek views. Chef's kitchen with Miele appliances and soapstone counters. Lower level ADU with separate entrance — ideal for rental or guests. 2-car garage.",
        "features": ["adu", "miele appliances", "soapstone counters", "sound views", "separate entrance", "radiant heat"],
        "garage_spaces": 2,
        "has_pool": False,
        "hoa_monthly": None,
        "taxes_annual": 10200,
        "latitude": 47.6257,
        "longitude": -122.2923,
        "photos_count": 42,
        "listing_agent": "Kenji Yamamoto",
        "mls_number": "WA-7741098",
    },
    {
        "id": "sea-002",
        "address": "100 Republican St #1205",
        "city": "Seattle",
        "state": "WA",
        "zip_code": "98109",
        "price": 895000,
        "bedrooms": 2,
        "bathrooms": 2.0,
        "sqft": 1480,
        "lot_size_sqft": None,
        "year_built": 2018,
        "property_type": "condo",
        "status": "active",
        "days_on_market": 13,
        "description": "High-rise condo in South Lake Union with Queen Anne Hills and Space Needle views. Walnut cabinetry, quartz counters, and Bosch appliances. Floor-to-ceiling windows. Building has 24-hour concierge, gym, and sky deck.",
        "features": ["space needle views", "walnut cabinetry", "sky deck", "24-hour concierge", "gym", "floor-to-ceiling windows"],
        "garage_spaces": 1,
        "has_pool": False,
        "hoa_monthly": 740,
        "taxes_annual": 8700,
        "latitude": 47.6240,
        "longitude": -122.3389,
        "photos_count": 38,
        "listing_agent": "Mei Chen",
        "mls_number": "WA-7729034",
    },
    {
        "id": "sea-003",
        "address": "7614 35th Ave SW",
        "city": "Seattle",
        "state": "WA",
        "zip_code": "98126",
        "price": 795000,
        "bedrooms": 3,
        "bathrooms": 2.5,
        "sqft": 2100,
        "lot_size_sqft": 5000,
        "year_built": 2017,
        "property_type": "single_family",
        "status": "active",
        "days_on_market": 5,
        "description": "Contemporary home in West Seattle with Olympic Mountain views from rooftop deck. Open main floor with gas fireplace, quartz island, and stainless appliances. EV charging, solar panels, and battery storage.",
        "features": ["olympic mountain views", "rooftop deck", "solar panels", "ev charging", "battery storage", "gas fireplace"],
        "garage_spaces": 2,
        "has_pool": False,
        "hoa_monthly": None,
        "taxes_annual": 7100,
        "latitude": 47.5517,
        "longitude": -122.3734,
        "photos_count": 33,
        "listing_agent": "Anna Peterson",
        "mls_number": "WA-7758901",
    },
    {
        "id": "sea-004",
        "address": "1823 N 45th St",
        "city": "Seattle",
        "state": "WA",
        "zip_code": "98103",
        "price": 1350000,
        "bedrooms": 5,
        "bathrooms": 3.5,
        "sqft": 3400,
        "lot_size_sqft": 6800,
        "year_built": 2014,
        "property_type": "single_family",
        "status": "active",
        "days_on_market": 20,
        "description": "Elegant Craftsman in Wallingford with Lake Union and city views. Grand entry with custom millwork, chef's kitchen with marble island, and butler's pantry. Au pair suite on lower level. Landscaped yard with water feature.",
        "features": ["lake union views", "butler's pantry", "au pair suite", "marble island", "custom millwork", "water feature"],
        "garage_spaces": 2,
        "has_pool": False,
        "hoa_monthly": None,
        "taxes_annual": 11900,
        "latitude": 47.6601,
        "longitude": -122.3384,
        "photos_count": 50,
        "listing_agent": "Robert Kim",
        "mls_number": "WA-7712345",
    },
    {
        "id": "sea-005",
        "address": "219 1st Ave N #401",
        "city": "Seattle",
        "state": "WA",
        "zip_code": "98109",
        "price": 499000,
        "bedrooms": 1,
        "bathrooms": 1.0,
        "sqft": 780,
        "lot_size_sqft": None,
        "year_built": 2020,
        "property_type": "condo",
        "status": "active",
        "days_on_market": 9,
        "description": "Modern Queen Anne condo with gas range and in-unit washer/dryer. Private balcony with partial water views. Bike-friendly building with secure storage. Walk to Seattle Center, restaurants, and transit.",
        "features": ["gas range", "in-unit washer/dryer", "private balcony", "bike storage", "walk score 95"],
        "garage_spaces": 1,
        "has_pool": False,
        "hoa_monthly": 390,
        "taxes_annual": 4700,
        "latitude": 47.6237,
        "longitude": -122.3546,
        "photos_count": 22,
        "listing_agent": "Sarah Park",
        "mls_number": "WA-7771289",
    },
    # ─────────────────────────── CHICAGO, IL ───────────────────────────
    {
        "id": "chi-001",
        "address": "1600 N Lake Shore Dr #2402",
        "city": "Chicago",
        "state": "IL",
        "zip_code": "60614",
        "price": 875000,
        "bedrooms": 3,
        "bathrooms": 2.5,
        "sqft": 2200,
        "lot_size_sqft": None,
        "year_built": 1971,
        "property_type": "condo",
        "status": "active",
        "days_on_market": 25,
        "description": "Stunning Lake Shore Drive condo with sweeping Lake Michigan and city views. Gut-renovated with Eggersmann kitchen, marble baths, and wide-plank oak floors. Lincoln Park location. Full-service building with valet.",
        "features": ["lake michigan views", "eggersmann kitchen", "marble baths", "oak floors", "valet", "doorman"],
        "garage_spaces": 1,
        "has_pool": False,
        "hoa_monthly": 1850,
        "taxes_annual": 14200,
        "latitude": 41.9117,
        "longitude": -87.6298,
        "photos_count": 45,
        "listing_agent": "Victoria Lane",
        "mls_number": "IL-3312089",
    },
    {
        "id": "chi-002",
        "address": "2127 W Iowa St",
        "city": "Chicago",
        "state": "IL",
        "zip_code": "60622",
        "price": 649000,
        "bedrooms": 3,
        "bathrooms": 2.0,
        "sqft": 1900,
        "lot_size_sqft": 3200,
        "year_built": 2016,
        "property_type": "single_family",
        "status": "active",
        "days_on_market": 8,
        "description": "Three-story single-family in Wicker Park with two private outdoor spaces. Chef's kitchen with quartz and Bosch appliances, open living/dining with 10-foot ceilings, and rooftop deck. 2-car garage with EV charger.",
        "features": ["rooftop deck", "10-foot ceilings", "bosch appliances", "ev charger", "two outdoor spaces", "smart home"],
        "garage_spaces": 2,
        "has_pool": False,
        "hoa_monthly": None,
        "taxes_annual": 8900,
        "latitude": 41.8971,
        "longitude": -87.6782,
        "photos_count": 37,
        "listing_agent": "Owen Bradley",
        "mls_number": "IL-3328456",
    },
    {
        "id": "chi-003",
        "address": "111 W Wacker Dr #5501",
        "city": "Chicago",
        "state": "IL",
        "zip_code": "60601",
        "price": 1200000,
        "bedrooms": 3,
        "bathrooms": 3.0,
        "sqft": 2650,
        "lot_size_sqft": None,
        "year_built": 2022,
        "property_type": "condo",
        "status": "active",
        "days_on_market": 48,
        "description": "Brand-new ultra-luxury condo at One Chicago. Stunning Chicago River and Lake Michigan views. Custom Poggenpohl kitchen with Miele appliances, heated marble floors. 5-star amenities: indoor pool, spa, private dining.",
        "features": ["chicago river views", "lake michigan views", "poggenpohl kitchen", "heated floors", "indoor pool", "private dining"],
        "garage_spaces": 2,
        "has_pool": True,
        "hoa_monthly": 2200,
        "taxes_annual": 18900,
        "latitude": 41.8865,
        "longitude": -87.6345,
        "photos_count": 65,
        "listing_agent": "Elena Marks",
        "mls_number": "IL-3301234",
    },
    {
        "id": "chi-004",
        "address": "4512 N Paulina St",
        "city": "Chicago",
        "state": "IL",
        "zip_code": "60640",
        "price": 725000,
        "bedrooms": 4,
        "bathrooms": 3.5,
        "sqft": 2800,
        "lot_size_sqft": 2500,
        "year_built": 2019,
        "property_type": "single_family",
        "status": "active",
        "days_on_market": 14,
        "description": "Newer construction in vibrant Ravenswood. Four levels of living with private rooftop deck, heated 2-car garage, and finished lower level. Primary suite occupies full upper floor with walk-in closet and spa bath.",
        "features": ["four levels", "rooftop deck", "heated garage", "finished lower level", "spa bath", "walk-in closet"],
        "garage_spaces": 2,
        "has_pool": False,
        "hoa_monthly": None,
        "taxes_annual": 10200,
        "latitude": 41.9652,
        "longitude": -87.6714,
        "photos_count": 40,
        "listing_agent": "Patrick Dunn",
        "mls_number": "IL-3341205",
    },
    {
        "id": "chi-005",
        "address": "123 N Jefferson St #1804",
        "city": "Chicago",
        "state": "IL",
        "zip_code": "60661",
        "price": 479000,
        "bedrooms": 2,
        "bathrooms": 2.0,
        "sqft": 1180,
        "lot_size_sqft": None,
        "year_built": 2018,
        "property_type": "condo",
        "status": "active",
        "days_on_market": 17,
        "description": "West Loop condo steps from Randolph Street Restaurant Row. Sleek kitchen with waterfall quartz island, Bosch appliances. Wide-plank hardwood throughout. Private balcony. Building amenities: pool, dog run, coworking space.",
        "features": ["waterfall island", "hardwood floors", "private balcony", "pool", "dog run", "coworking space"],
        "garage_spaces": 1,
        "has_pool": True,
        "hoa_monthly": 510,
        "taxes_annual": 7600,
        "latitude": 41.8837,
        "longitude": -87.6420,
        "photos_count": 30,
        "listing_agent": "Grace Wong",
        "mls_number": "IL-3355890",
    },
    # ─────────────────────────── RALEIGH, NC ───────────────────────────
    {
        "id": "rdv-001",
        "address": "3102 Glen Eden Dr",
        "city": "Raleigh",
        "state": "NC",
        "zip_code": "27612",
        "price": 695000,
        "bedrooms": 4,
        "bathrooms": 3.5,
        "sqft": 3100,
        "lot_size_sqft": 11200,
        "year_built": 2020,
        "property_type": "single_family",
        "status": "active",
        "days_on_market": 10,
        "description": "Craftsman home in Highgate at North Hills. Open floor plan, chef's kitchen with gas range and quartz counters. Main-level primary suite, screened porch, and covered patio overlooking flat backyard.",
        "features": ["main-level primary", "screened porch", "gas range", "quartz counters", "flat backyard", "smart home"],
        "garage_spaces": 2,
        "has_pool": False,
        "hoa_monthly": 165,
        "taxes_annual": 4800,
        "latitude": 35.8634,
        "longitude": -78.7012,
        "photos_count": 36,
        "listing_agent": "Tony Whitfield",
        "mls_number": "NC-5592012",
    },
    {
        "id": "rdv-002",
        "address": "516 W Lenoir St",
        "city": "Raleigh",
        "state": "NC",
        "zip_code": "27601",
        "price": 525000,
        "bedrooms": 3,
        "bathrooms": 2.5,
        "sqft": 2050,
        "lot_size_sqft": 3800,
        "year_built": 2021,
        "property_type": "townhouse",
        "status": "active",
        "days_on_market": 6,
        "description": "Luxury townhome steps from Raleigh's Warehouse District and Glenwood South. Three stories of elevated living: gourmet kitchen on main, rooftop terrace, and ground-floor flex space. 2-car attached garage.",
        "features": ["rooftop terrace", "gourmet kitchen", "flex space", "attached garage", "urban location"],
        "garage_spaces": 2,
        "has_pool": False,
        "hoa_monthly": 250,
        "taxes_annual": 3600,
        "latitude": 35.7735,
        "longitude": -78.6472,
        "photos_count": 28,
        "listing_agent": "Hannah Simmons",
        "mls_number": "IL-5581345",
    },
    {
        "id": "rdv-003",
        "address": "9801 Durant Rd",
        "city": "Raleigh",
        "state": "NC",
        "zip_code": "27614",
        "price": 895000,
        "bedrooms": 5,
        "bathrooms": 4.0,
        "sqft": 4200,
        "lot_size_sqft": 22000,
        "year_built": 2015,
        "property_type": "single_family",
        "status": "active",
        "days_on_market": 23,
        "description": "Executive home on private half-acre lot in North Raleigh. Brick exterior, grand entry, and chef's kitchen. Finished basement with media room and gym. Screened porch overlooking heated pool and spa.",
        "features": ["half-acre lot", "media room", "gym", "screened porch", "heated pool", "spa"],
        "garage_spaces": 3,
        "has_pool": True,
        "hoa_monthly": 195,
        "taxes_annual": 6200,
        "latitude": 35.9001,
        "longitude": -78.6831,
        "photos_count": 46,
        "listing_agent": "David Cline",
        "mls_number": "NC-5564201",
    },
    {
        "id": "rdv-004",
        "address": "222 Glenwood Ave #304",
        "city": "Raleigh",
        "state": "NC",
        "zip_code": "27603",
        "price": 385000,
        "bedrooms": 1,
        "bathrooms": 1.0,
        "sqft": 900,
        "lot_size_sqft": None,
        "year_built": 2023,
        "property_count": 1,
        "property_type": "condo",
        "status": "active",
        "days_on_market": 4,
        "description": "Brand-new condo in the heart of downtown Raleigh's Glenwood South entertainment district. Sleek kitchen with waterfall island, spa bath. Building features rooftop pool with city views, gym, and co-working lounge.",
        "features": ["rooftop pool", "city views", "gym", "co-working lounge", "new construction", "waterfall island"],
        "garage_spaces": 1,
        "has_pool": True,
        "hoa_monthly": 340,
        "taxes_annual": 2700,
        "latitude": 35.7821,
        "longitude": -78.6524,
        "photos_count": 20,
        "listing_agent": "Kylie Marsh",
        "mls_number": "NC-5598760",
    },
    # ─────────────────────────── PORTLAND, OR ───────────────────────────
    {
        "id": "pdx-001",
        "address": "3456 NE Alberta St",
        "city": "Portland",
        "state": "OR",
        "zip_code": "97211",
        "price": 620000,
        "bedrooms": 3,
        "bathrooms": 2.0,
        "sqft": 1850,
        "lot_size_sqft": 5200,
        "year_built": 1922,
        "property_type": "single_family",
        "status": "active",
        "days_on_market": 9,
        "description": "Fully restored 1920s Craftsman bungalow on Alberta Arts District. Original fir floors, built-in bookcases, and arched doorways. New roof, new electrical, remodeled kitchen and baths. Detached studio/ADU.",
        "features": ["original fir floors", "built-in bookcases", "detached studio", "adu", "new roof", "arched doorways"],
        "garage_spaces": 0,
        "has_pool": False,
        "hoa_monthly": None,
        "taxes_annual": 7200,
        "latitude": 45.5579,
        "longitude": -122.6338,
        "photos_count": 34,
        "listing_agent": "Colin Reed",
        "mls_number": "OR-8821034",
    },
    {
        "id": "pdx-002",
        "address": "1234 SW Jefferson St #601",
        "city": "Portland",
        "state": "OR",
        "zip_code": "97201",
        "price": 545000,
        "bedrooms": 2,
        "bathrooms": 2.0,
        "sqft": 1350,
        "lot_size_sqft": None,
        "year_built": 2019,
        "property_type": "condo",
        "status": "active",
        "days_on_market": 15,
        "description": "Upscale condo in Portland's vibrant West End. Floor-to-ceiling windows with Willamette River views. Chef's kitchen with Italian cabinetry and gas range. Building features rooftop deck, Peloton gym, and concierge.",
        "features": ["willamette river views", "italian cabinetry", "rooftop deck", "peloton gym", "concierge", "floor-to-ceiling windows"],
        "garage_spaces": 1,
        "has_pool": False,
        "hoa_monthly": 595,
        "taxes_annual": 9800,
        "latitude": 45.5168,
        "longitude": -122.6895,
        "photos_count": 30,
        "listing_agent": "Abby Tran",
        "mls_number": "OR-8834590",
    },
    {
        "id": "pdx-003",
        "address": "5801 SE Division St",
        "city": "Portland",
        "state": "OR",
        "zip_code": "97206",
        "price": 485000,
        "bedrooms": 3,
        "bathrooms": 1.5,
        "sqft": 1680,
        "lot_size_sqft": 4800,
        "year_built": 1948,
        "property_type": "single_family",
        "status": "active",
        "days_on_market": 4,
        "description": "Classic postwar bungalow on SE Division with updated kitchen and baths. Hardwood floors, gas fireplace, and sunroom addition. Large fully fenced yard. Steps to Portland's most celebrated restaurant corridor.",
        "features": ["hardwood floors", "gas fireplace", "sunroom", "fenced yard", "updated kitchen"],
        "garage_spaces": 1,
        "has_pool": False,
        "hoa_monthly": None,
        "taxes_annual": 6900,
        "latitude": 45.5003,
        "longitude": -122.6010,
        "photos_count": 26,
        "listing_agent": "James Lin",
        "mls_number": "OR-8857823",
    },
    {
        "id": "pdx-004",
        "address": "2200 NW Westover Rd",
        "city": "Portland",
        "state": "OR",
        "zip_code": "97210",
        "price": 1150000,
        "bedrooms": 5,
        "bathrooms": 4.0,
        "sqft": 4100,
        "lot_size_sqft": 15000,
        "year_built": 2006,
        "property_type": "single_family",
        "status": "active",
        "days_on_market": 30,
        "description": "Stunning contemporary home in Westover Heights with panoramic views of Portland, the Willamette Valley, and Mount Hood. Chef's kitchen, wine room, home theater, and tiered decks. Heated driveway and 3-car garage.",
        "features": ["panoramic portland views", "mount hood views", "wine room", "home theater", "tiered decks", "heated driveway"],
        "garage_spaces": 3,
        "has_pool": False,
        "hoa_monthly": None,
        "taxes_annual": 15800,
        "latitude": 45.5341,
        "longitude": -122.7098,
        "photos_count": 55,
        "listing_agent": "Helen Burke",
        "mls_number": "OR-8801456",
    },
    # ─────────────────────────── BOSTON, MA ───────────────────────────
    {
        "id": "bos-001",
        "address": "55 Commonwealth Ave #2",
        "city": "Boston",
        "state": "MA",
        "zip_code": "02116",
        "price": 1750000,
        "bedrooms": 3,
        "bathrooms": 2.5,
        "sqft": 2100,
        "lot_size_sqft": None,
        "year_built": 1880,
        "property_type": "condo",
        "status": "active",
        "days_on_market": 11,
        "description": "Gorgeous floor-through brownstone condo on coveted Commonwealth Avenue mall. Preserved original details: 12-foot coffered ceilings, plaster medallions, and marble fireplaces. Fully modernized kitchen and baths. Private parking.",
        "features": ["commonwealth ave mall", "coffered ceilings", "marble fireplaces", "plaster medallions", "private parking", "renovated"],
        "garage_spaces": 1,
        "has_pool": False,
        "hoa_monthly": 550,
        "taxes_annual": 19800,
        "latitude": 42.3527,
        "longitude": -71.0836,
        "photos_count": 48,
        "listing_agent": "Margaret Walsh",
        "mls_number": "MA-1102890",
    },
    {
        "id": "bos-002",
        "address": "14 Louisburg Sq",
        "city": "Boston",
        "state": "MA",
        "zip_code": "02108",
        "price": 4200000,
        "bedrooms": 5,
        "bathrooms": 4.5,
        "sqft": 4800,
        "lot_size_sqft": 2800,
        "year_built": 1848,
        "property_type": "single_family",
        "status": "active",
        "days_on_market": 62,
        "description": "Once-in-a-generation opportunity on Beacon Hill's Louisburg Square, Boston's most prestigious private park. Landmark Greek Revival with exceptional proportions and impeccable restoration. Five fireplaces, bespoke library, and chef's kitchen.",
        "features": ["louisburg square", "five fireplaces", "bespoke library", "private park access", "landmark architecture", "chef's kitchen"],
        "garage_spaces": 2,
        "has_pool": False,
        "hoa_monthly": 300,
        "taxes_annual": 42000,
        "latitude": 42.3575,
        "longitude": -71.0682,
        "photos_count": 80,
        "listing_agent": "Harrison Foote",
        "mls_number": "MA-1088023",
    },
    {
        "id": "bos-003",
        "address": "400 Stuart St #34C",
        "city": "Boston",
        "state": "MA",
        "zip_code": "02116",
        "price": 1100000,
        "bedrooms": 2,
        "bathrooms": 2.0,
        "sqft": 1620,
        "lot_size_sqft": None,
        "year_built": 2020,
        "property_type": "condo",
        "status": "active",
        "days_on_market": 18,
        "description": "Luxury high-rise condo in Back Bay's Raffles Residences. Stunning views of the Charles River and Back Bay skyline. Poggenpohl kitchen with Miele appliances. Access to Raffles Hotel amenities including spa, pool, and fine dining.",
        "features": ["charles river views", "raffles hotel amenities", "poggenpohl kitchen", "miele appliances", "spa access", "fine dining"],
        "garage_spaces": 1,
        "has_pool": True,
        "hoa_monthly": 2100,
        "taxes_annual": 13500,
        "latitude": 42.3495,
        "longitude": -71.0724,
        "photos_count": 50,
        "listing_agent": "Claire Reilly",
        "mls_number": "MA-1115670",
    },
    {
        "id": "bos-004",
        "address": "24 Howland St",
        "city": "Boston",
        "state": "MA",
        "zip_code": "02121",
        "price": 699000,
        "bedrooms": 4,
        "bathrooms": 2.0,
        "sqft": 1850,
        "lot_size_sqft": 3200,
        "year_built": 1905,
        "property_type": "single_family",
        "status": "active",
        "days_on_market": 6,
        "description": "Victorian detached home in Dorchester, fully renovated. New kitchen with quartz and shaker cabinets, two updated baths, refinished hardwood floors throughout. Private backyard deck. Minutes to JFK/UMass Red Line.",
        "features": ["fully renovated", "quartz counters", "refinished hardwoods", "private deck", "red line access"],
        "garage_spaces": 0,
        "has_pool": False,
        "hoa_monthly": None,
        "taxes_annual": 7800,
        "latitude": 42.3103,
        "longitude": -71.0628,
        "photos_count": 27,
        "listing_agent": "Keith Adamo",
        "mls_number": "MA-1128912",
    },
    {
        "id": "bos-005",
        "address": "2 Avery St #29A",
        "city": "Boston",
        "state": "MA",
        "zip_code": "02111",
        "price": 850000,
        "bedrooms": 1,
        "bathrooms": 1.5,
        "sqft": 1050,
        "lot_size_sqft": None,
        "year_built": 2014,
        "property_type": "condo",
        "status": "active",
        "days_on_market": 14,
        "description": "Sophisticated Millennium Place high-rise condo in the heart of Downtown Boston. European kitchen with Miele appliances, floor-to-ceiling windows. Access to Equinox fitness club, indoor pool, and spa. Steps to the Common.",
        "features": ["equinox fitness", "indoor pool", "spa", "miele appliances", "floor-to-ceiling windows", "downtown location"],
        "garage_spaces": 1,
        "has_pool": True,
        "hoa_monthly": 1600,
        "taxes_annual": 9900,
        "latitude": 42.3540,
        "longitude": -71.0616,
        "photos_count": 36,
        "listing_agent": "Nora Cassidy",
        "mls_number": "MA-1101345",
    },
    # ─────────────────────────── ATLANTA, GA ───────────────────────────
    {
        "id": "atl-001",
        "address": "3845 Peachtree Rd NE",
        "city": "Atlanta",
        "state": "GA",
        "zip_code": "30319",
        "price": 1050000,
        "bedrooms": 5,
        "bathrooms": 4.5,
        "sqft": 4600,
        "lot_size_sqft": 13500,
        "year_built": 2018,
        "property_type": "single_family",
        "status": "active",
        "days_on_market": 21,
        "description": "Traditional luxury home in Brookhaven with beautiful yard and pool. Chef's kitchen with Thermador appliances, keeping room, and butler's pantry. Main-level guest suite. Finished basement with bar and gym.",
        "features": ["thermador appliances", "keeping room", "butler's pantry", "main-level guest suite", "finished basement", "gym"],
        "garage_spaces": 3,
        "has_pool": True,
        "hoa_monthly": 125,
        "taxes_annual": 9400,
        "latitude": 33.8648,
        "longitude": -84.3507,
        "photos_count": 52,
        "listing_agent": "Whitney James",
        "mls_number": "GA-4421078",
    },
    {
        "id": "atl-002",
        "address": "788 West Marietta St NW",
        "city": "Atlanta",
        "state": "GA",
        "zip_code": "30318",
        "price": 575000,
        "bedrooms": 3,
        "bathrooms": 3.5,
        "sqft": 2280,
        "lot_size_sqft": 2800,
        "year_built": 2022,
        "property_type": "townhouse",
        "status": "active",
        "days_on_market": 12,
        "description": "New construction end-unit townhome in West Midtown's ArtStreet community. Four levels with private rooftop terrace. Chef's kitchen with Thermador range, quartz counters, and custom cabinetry. Attached 2-car garage.",
        "features": ["rooftop terrace", "thermador range", "custom cabinetry", "end unit", "4 levels", "ev ready"],
        "garage_spaces": 2,
        "has_pool": False,
        "hoa_monthly": 300,
        "taxes_annual": 5100,
        "latitude": 33.7840,
        "longitude": -84.4108,
        "photos_count": 32,
        "listing_agent": "Steven Okafor",
        "mls_number": "GA-4438901",
    },
    {
        "id": "atl-003",
        "address": "805 Peachtree St NE #1602",
        "city": "Atlanta",
        "state": "GA",
        "zip_code": "30308",
        "price": 430000,
        "bedrooms": 2,
        "bathrooms": 2.0,
        "sqft": 1200,
        "lot_size_sqft": None,
        "year_built": 2020,
        "property_type": "condo",
        "status": "active",
        "days_on_market": 8,
        "description": "Stunning Midtown Atlanta high-rise condo with Piedmont Park views. Sub-Zero refrigerator, Wolf gas range, and quartz waterfall island. Building features 24-hour concierge, resort-style pool, and state-of-the-art gym.",
        "features": ["piedmont park views", "sub-zero refrigerator", "wolf range", "resort-style pool", "24-hour concierge", "state-of-the-art gym"],
        "garage_spaces": 1,
        "has_pool": True,
        "hoa_monthly": 580,
        "taxes_annual": 5300,
        "latitude": 33.7739,
        "longitude": -84.3834,
        "photos_count": 33,
        "listing_agent": "Ava Brown",
        "mls_number": "GA-4451234",
    },
    {
        "id": "atl-004",
        "address": "1234 Clifton Rd NE",
        "city": "Atlanta",
        "state": "GA",
        "zip_code": "30307",
        "price": 799000,
        "bedrooms": 4,
        "bathrooms": 3.0,
        "sqft": 2900,
        "lot_size_sqft": 9200,
        "year_built": 1960,
        "property_type": "single_family",
        "status": "active",
        "days_on_market": 5,
        "description": "Beautifully renovated ranch in Druid Hills historic district, near Emory University. Open-concept renovation preserves original character while adding modern chef's kitchen and spa primary suite. Covered patio and pool.",
        "features": ["historic district", "open-concept renovation", "chef's kitchen", "spa suite", "covered patio", "near emory"],
        "garage_spaces": 2,
        "has_pool": True,
        "hoa_monthly": None,
        "taxes_annual": 7100,
        "latitude": 33.7748,
        "longitude": -84.3285,
        "photos_count": 38,
        "listing_agent": "Marcus Young",
        "mls_number": "GA-4462890",
    },
    {
        "id": "atl-005",
        "address": "199 14th St NE #903",
        "city": "Atlanta",
        "state": "GA",
        "zip_code": "30309",
        "price": 365000,
        "bedrooms": 1,
        "bathrooms": 1.0,
        "sqft": 850,
        "lot_size_sqft": None,
        "year_built": 2018,
        "property_type": "condo",
        "status": "active",
        "days_on_market": 3,
        "description": "Modern Midtown condo with Peachtree strip and cityscape views. Quartz kitchen with integrated appliances. Floor-to-ceiling windows. Building features saltwater pool, sun deck, and yoga studio. Beltline access steps away.",
        "features": ["beltline access", "saltwater pool", "yoga studio", "sun deck", "integrated appliances", "city views"],
        "garage_spaces": 1,
        "has_pool": True,
        "hoa_monthly": 415,
        "taxes_annual": 4200,
        "latitude": 33.7876,
        "longitude": -84.3831,
        "photos_count": 22,
        "listing_agent": "Janelle Fox",
        "mls_number": "GA-4473456",
    },
]

# ─────────────────────── PRICE HISTORY DATABASE ───────────────────────

PRICE_HISTORIES: Dict[str, Dict] = {
    "atx-001": {
        "property_id": "atx-001",
        "address": "2847 Barton Hills Dr, Austin, TX 78704",
        "current_price": 875000,
        "original_list_price": 925000,
        "history": [
            {"date": "2024-01-15", "price": 925000, "event": "Listed", "price_change": None, "price_change_pct": None},
            {"date": "2024-02-05", "price": 899000, "event": "Price Reduced", "price_change": -26000, "price_change_pct": -2.8},
            {"date": "2024-03-18", "price": 875000, "event": "Price Reduced", "price_change": -24000, "price_change_pct": -2.7},
        ],
        "total_price_changes": 2,
        "days_on_market": 12,
    },
    "bos-002": {
        "property_id": "bos-002",
        "address": "14 Louisburg Sq, Boston, MA 02108",
        "current_price": 4200000,
        "original_list_price": 4500000,
        "history": [
            {"date": "2024-02-01", "price": 4500000, "event": "Listed", "price_change": None, "price_change_pct": None},
            {"date": "2024-03-10", "price": 4350000, "event": "Price Reduced", "price_change": -150000, "price_change_pct": -3.3},
            {"date": "2024-04-01", "price": 4200000, "event": "Price Reduced", "price_change": -150000, "price_change_pct": -3.4},
        ],
        "total_price_changes": 2,
        "days_on_market": 62,
    },
    "mia-001": {
        "property_id": "mia-001",
        "address": "1100 Brickell Bay Dr #4801, Miami, FL 33131",
        "current_price": 2100000,
        "original_list_price": 2350000,
        "history": [
            {"date": "2023-12-01", "price": 2350000, "event": "Listed", "price_change": None, "price_change_pct": None},
            {"date": "2024-01-15", "price": 2200000, "event": "Price Reduced", "price_change": -150000, "price_change_pct": -6.4},
            {"date": "2024-02-20", "price": 2100000, "event": "Price Reduced", "price_change": -100000, "price_change_pct": -4.5},
        ],
        "total_price_changes": 2,
        "days_on_market": 42,
    },
}

# ─────────────────────── MARKET STATS DATABASE ───────────────────────

MARKET_STATS: Dict[str, Dict] = {
    "Austin": {
        "city": "Austin",
        "state": "TX",
        "report_date": "2025-03-01",
        "active_listings": 4218,
        "median_list_price": 589000,
        "median_sale_price": 571000,
        "avg_days_on_market": 38.2,
        "months_of_supply": 3.8,
        "list_to_sale_ratio": 0.97,
        "price_per_sqft": 312,
        "sold_last_30_days": 892,
        "new_listings_last_30_days": 1104,
        "market_type": "balanced",
        "yoy_price_change_pct": -4.2,
        "by_property_type": {
            "single_family": {"median_price": 672000, "count": 2841},
            "condo": {"median_price": 410000, "count": 897},
            "townhouse": {"median_price": 485000, "count": 480},
        },
    },
    "Denver": {
        "city": "Denver",
        "state": "CO",
        "report_date": "2025-03-01",
        "active_listings": 3102,
        "median_list_price": 589000,
        "median_sale_price": 568000,
        "avg_days_on_market": 28.4,
        "months_of_supply": 2.9,
        "list_to_sale_ratio": 0.985,
        "price_per_sqft": 328,
        "sold_last_30_days": 1041,
        "new_listings_last_30_days": 1198,
        "market_type": "sellers",
        "yoy_price_change_pct": 1.8,
        "by_property_type": {
            "single_family": {"median_price": 710000, "count": 1890},
            "condo": {"median_price": 410000, "count": 798},
            "townhouse": {"median_price": 520000, "count": 414},
        },
    },
    "Nashville": {
        "city": "Nashville",
        "state": "TN",
        "report_date": "2025-03-01",
        "active_listings": 3487,
        "median_list_price": 510000,
        "median_sale_price": 492000,
        "avg_days_on_market": 34.1,
        "months_of_supply": 3.5,
        "list_to_sale_ratio": 0.973,
        "price_per_sqft": 258,
        "sold_last_30_days": 978,
        "new_listings_last_30_days": 1143,
        "market_type": "balanced",
        "yoy_price_change_pct": -1.9,
        "by_property_type": {
            "single_family": {"median_price": 598000, "count": 2298},
            "condo": {"median_price": 425000, "count": 742},
            "townhouse": {"median_price": 488000, "count": 447},
        },
    },
    "Charlotte": {
        "city": "Charlotte",
        "state": "NC",
        "report_date": "2025-03-01",
        "active_listings": 4891,
        "median_list_price": 425000,
        "median_sale_price": 408000,
        "avg_days_on_market": 24.8,
        "months_of_supply": 2.6,
        "list_to_sale_ratio": 0.992,
        "price_per_sqft": 211,
        "sold_last_30_days": 1789,
        "new_listings_last_30_days": 2201,
        "market_type": "sellers",
        "yoy_price_change_pct": 4.1,
        "by_property_type": {
            "single_family": {"median_price": 498000, "count": 3201},
            "condo": {"median_price": 318000, "count": 1043},
            "townhouse": {"median_price": 358000, "count": 647},
        },
    },
    "Phoenix": {
        "city": "Phoenix",
        "state": "AZ",
        "report_date": "2025-03-01",
        "active_listings": 8924,
        "median_list_price": 478000,
        "median_sale_price": 458000,
        "avg_days_on_market": 42.3,
        "months_of_supply": 4.8,
        "list_to_sale_ratio": 0.963,
        "price_per_sqft": 238,
        "sold_last_30_days": 2891,
        "new_listings_last_30_days": 3240,
        "market_type": "buyers",
        "yoy_price_change_pct": -2.8,
        "by_property_type": {
            "single_family": {"median_price": 528000, "count": 6102},
            "condo": {"median_price": 298000, "count": 1890},
            "townhouse": {"median_price": 378000, "count": 932},
        },
    },
    "Miami": {
        "city": "Miami",
        "state": "FL",
        "report_date": "2025-03-01",
        "active_listings": 11230,
        "median_list_price": 635000,
        "median_sale_price": 598000,
        "avg_days_on_market": 61.2,
        "months_of_supply": 6.1,
        "list_to_sale_ratio": 0.952,
        "price_per_sqft": 498,
        "sold_last_30_days": 1842,
        "new_listings_last_30_days": 2790,
        "market_type": "buyers",
        "yoy_price_change_pct": -3.9,
        "by_property_type": {
            "single_family": {"median_price": 895000, "count": 4501},
            "condo": {"median_price": 545000, "count": 5901},
            "townhouse": {"median_price": 498000, "count": 828},
        },
    },
    "Seattle": {
        "city": "Seattle",
        "state": "WA",
        "report_date": "2025-03-01",
        "active_listings": 2418,
        "median_list_price": 818000,
        "median_sale_price": 825000,
        "avg_days_on_market": 16.3,
        "months_of_supply": 1.4,
        "list_to_sale_ratio": 1.022,
        "price_per_sqft": 568,
        "sold_last_30_days": 1718,
        "new_listings_last_30_days": 1401,
        "market_type": "sellers",
        "yoy_price_change_pct": 6.3,
        "by_property_type": {
            "single_family": {"median_price": 1050000, "count": 1289},
            "condo": {"median_price": 598000, "count": 841},
            "townhouse": {"median_price": 798000, "count": 288},
        },
    },
    "Chicago": {
        "city": "Chicago",
        "state": "IL",
        "report_date": "2025-03-01",
        "active_listings": 5891,
        "median_list_price": 395000,
        "median_sale_price": 381000,
        "avg_days_on_market": 31.9,
        "months_of_supply": 3.1,
        "list_to_sale_ratio": 0.978,
        "price_per_sqft": 234,
        "sold_last_30_days": 1898,
        "new_listings_last_30_days": 2140,
        "market_type": "balanced",
        "yoy_price_change_pct": 2.1,
        "by_property_type": {
            "single_family": {"median_price": 498000, "count": 2901},
            "condo": {"median_price": 298000, "count": 2441},
            "townhouse": {"median_price": 435000, "count": 549},
        },
    },
    "Raleigh": {
        "city": "Raleigh",
        "state": "NC",
        "report_date": "2025-03-01",
        "active_listings": 3241,
        "median_list_price": 438000,
        "median_sale_price": 421000,
        "avg_days_on_market": 22.7,
        "months_of_supply": 2.4,
        "list_to_sale_ratio": 0.994,
        "price_per_sqft": 218,
        "sold_last_30_days": 1348,
        "new_listings_last_30_days": 1502,
        "market_type": "sellers",
        "yoy_price_change_pct": 5.2,
        "by_property_type": {
            "single_family": {"median_price": 518000, "count": 2102},
            "condo": {"median_price": 325000, "count": 702},
            "townhouse": {"median_price": 385000, "count": 437},
        },
    },
    "Portland": {
        "city": "Portland",
        "state": "OR",
        "report_date": "2025-03-01",
        "active_listings": 3018,
        "median_list_price": 519000,
        "median_sale_price": 498000,
        "avg_days_on_market": 29.8,
        "months_of_supply": 3.2,
        "list_to_sale_ratio": 0.981,
        "price_per_sqft": 302,
        "sold_last_30_days": 941,
        "new_listings_last_30_days": 1098,
        "market_type": "balanced",
        "yoy_price_change_pct": 0.9,
        "by_property_type": {
            "single_family": {"median_price": 628000, "count": 1842},
            "condo": {"median_price": 398000, "count": 748},
            "townhouse": {"median_price": 478000, "count": 428},
        },
    },
    "Boston": {
        "city": "Boston",
        "state": "MA",
        "report_date": "2025-03-01",
        "active_listings": 1842,
        "median_list_price": 825000,
        "median_sale_price": 838000,
        "avg_days_on_market": 18.4,
        "months_of_supply": 1.7,
        "list_to_sale_ratio": 1.018,
        "price_per_sqft": 712,
        "sold_last_30_days": 1098,
        "new_listings_last_30_days": 892,
        "market_type": "sellers",
        "yoy_price_change_pct": 7.1,
        "by_property_type": {
            "single_family": {"median_price": 1100000, "count": 588},
            "condo": {"median_price": 748000, "count": 1041},
            "townhouse": {"median_price": 895000, "count": 213},
        },
    },
    "Atlanta": {
        "city": "Atlanta",
        "state": "GA",
        "report_date": "2025-03-01",
        "active_listings": 6102,
        "median_list_price": 389000,
        "median_sale_price": 372000,
        "avg_days_on_market": 27.4,
        "months_of_supply": 3.0,
        "list_to_sale_ratio": 0.983,
        "price_per_sqft": 194,
        "sold_last_30_days": 2141,
        "new_listings_last_30_days": 2498,
        "market_type": "balanced",
        "yoy_price_change_pct": 3.4,
        "by_property_type": {
            "single_family": {"median_price": 468000, "count": 3902},
            "condo": {"median_price": 298000, "count": 1541},
            "townhouse": {"median_price": 378000, "count": 659},
        },
    },
}

# ─────────────────────── NEIGHBORHOOD TRENDS ───────────────────────

NEIGHBORHOOD_TRENDS: Dict[str, Dict] = {
    "78704": {
        "zip_code": "78704",
        "neighborhood": "South Congress / Barton Hills",
        "city": "Austin",
        "state": "TX",
        "report_date": "2025-03-01",
        "walk_score": 82,
        "transit_score": 51,
        "school_rating": 8.1,
        "median_household_income": 94200,
        "population": 18400,
        "median_age": 34.2,
        "yoy_price_change_pct": -5.8,
        "five_year_price_change_pct": 42.3,
        "avg_price_per_sqft": 498,
        "rental_vacancy_rate": 4.2,
        "owner_occupied_pct": 41.8,
        "crime_index": 28,
        "nearby_amenities": {
            "grocery_stores": 8,
            "restaurants": 142,
            "parks": 12,
            "schools": 6,
            "hospitals": 2,
            "gyms": 15,
        },
    },
    "80202": {
        "zip_code": "80202",
        "neighborhood": "Lower Downtown (LoDo)",
        "city": "Denver",
        "state": "CO",
        "report_date": "2025-03-01",
        "walk_score": 95,
        "transit_score": 89,
        "school_rating": 6.8,
        "median_household_income": 110400,
        "population": 8200,
        "median_age": 33.8,
        "yoy_price_change_pct": 2.1,
        "five_year_price_change_pct": 28.9,
        "avg_price_per_sqft": 498,
        "rental_vacancy_rate": 6.8,
        "owner_occupied_pct": 38.2,
        "crime_index": 41,
        "nearby_amenities": {
            "grocery_stores": 6,
            "restaurants": 220,
            "parks": 8,
            "schools": 4,
            "hospitals": 3,
            "gyms": 22,
        },
    },
    "33131": {
        "zip_code": "33131",
        "neighborhood": "Brickell",
        "city": "Miami",
        "state": "FL",
        "report_date": "2025-03-01",
        "walk_score": 88,
        "transit_score": 74,
        "school_rating": 7.2,
        "median_household_income": 148000,
        "population": 22100,
        "median_age": 36.4,
        "yoy_price_change_pct": -6.1,
        "five_year_price_change_pct": 68.2,
        "avg_price_per_sqft": 892,
        "rental_vacancy_rate": 8.4,
        "owner_occupied_pct": 28.1,
        "crime_index": 38,
        "nearby_amenities": {
            "grocery_stores": 9,
            "restaurants": 198,
            "parks": 6,
            "schools": 8,
            "hospitals": 4,
            "gyms": 28,
        },
    },
    "98112": {
        "zip_code": "98112",
        "neighborhood": "Madison Valley / Capitol Hill",
        "city": "Seattle",
        "state": "WA",
        "report_date": "2025-03-01",
        "walk_score": 87,
        "transit_score": 64,
        "school_rating": 8.9,
        "median_household_income": 128000,
        "population": 19800,
        "median_age": 38.1,
        "yoy_price_change_pct": 7.4,
        "five_year_price_change_pct": 38.1,
        "avg_price_per_sqft": 598,
        "rental_vacancy_rate": 3.1,
        "owner_occupied_pct": 52.4,
        "crime_index": 22,
        "nearby_amenities": {
            "grocery_stores": 12,
            "restaurants": 168,
            "parks": 18,
            "schools": 9,
            "hospitals": 3,
            "gyms": 19,
        },
    },
    "02116": {
        "zip_code": "02116",
        "neighborhood": "Back Bay",
        "city": "Boston",
        "state": "MA",
        "report_date": "2025-03-01",
        "walk_score": 99,
        "transit_score": 93,
        "school_rating": 8.6,
        "median_household_income": 162000,
        "population": 21400,
        "median_age": 34.9,
        "yoy_price_change_pct": 8.2,
        "five_year_price_change_pct": 31.7,
        "avg_price_per_sqft": 924,
        "rental_vacancy_rate": 3.8,
        "owner_occupied_pct": 29.6,
        "crime_index": 15,
        "nearby_amenities": {
            "grocery_stores": 11,
            "restaurants": 312,
            "parks": 14,
            "schools": 10,
            "hospitals": 6,
            "gyms": 34,
        },
    },
    "30319": {
        "zip_code": "30319",
        "neighborhood": "Brookhaven",
        "city": "Atlanta",
        "state": "GA",
        "report_date": "2025-03-01",
        "walk_score": 71,
        "transit_score": 42,
        "school_rating": 8.4,
        "median_household_income": 118000,
        "population": 32100,
        "median_age": 37.2,
        "yoy_price_change_pct": 4.9,
        "five_year_price_change_pct": 29.8,
        "avg_price_per_sqft": 268,
        "rental_vacancy_rate": 4.8,
        "owner_occupied_pct": 61.2,
        "crime_index": 19,
        "nearby_amenities": {
            "grocery_stores": 14,
            "restaurants": 128,
            "parks": 21,
            "schools": 12,
            "hospitals": 3,
            "gyms": 16,
        },
    },
    "37220": {
        "zip_code": "37220",
        "neighborhood": "Oak Hill",
        "city": "Nashville",
        "state": "TN",
        "report_date": "2025-03-01",
        "walk_score": 42,
        "transit_score": 18,
        "school_rating": 9.2,
        "median_household_income": 142000,
        "population": 14200,
        "median_age": 41.8,
        "yoy_price_change_pct": -0.8,
        "five_year_price_change_pct": 44.1,
        "avg_price_per_sqft": 312,
        "rental_vacancy_rate": 2.9,
        "owner_occupied_pct": 74.8,
        "crime_index": 8,
        "nearby_amenities": {
            "grocery_stores": 8,
            "restaurants": 64,
            "parks": 16,
            "schools": 8,
            "hospitals": 2,
            "gyms": 10,
        },
    },
    "28207": {
        "zip_code": "28207",
        "neighborhood": "Myers Park",
        "city": "Charlotte",
        "state": "NC",
        "report_date": "2025-03-01",
        "walk_score": 78,
        "transit_score": 38,
        "school_rating": 9.0,
        "median_household_income": 168000,
        "population": 16800,
        "median_age": 42.1,
        "yoy_price_change_pct": 5.6,
        "five_year_price_change_pct": 36.2,
        "avg_price_per_sqft": 328,
        "rental_vacancy_rate": 3.4,
        "owner_occupied_pct": 68.9,
        "crime_index": 12,
        "nearby_amenities": {
            "grocery_stores": 10,
            "restaurants": 98,
            "parks": 24,
            "schools": 11,
            "hospitals": 4,
            "gyms": 14,
        },
    },
    "85253": {
        "zip_code": "85253",
        "neighborhood": "Paradise Valley / North Scottsdale",
        "city": "Phoenix",
        "state": "AZ",
        "report_date": "2025-03-01",
        "walk_score": 38,
        "transit_score": 22,
        "school_rating": 9.1,
        "median_household_income": 198000,
        "population": 12400,
        "median_age": 48.2,
        "yoy_price_change_pct": -3.2,
        "five_year_price_change_pct": 51.4,
        "avg_price_per_sqft": 498,
        "rental_vacancy_rate": 4.8,
        "owner_occupied_pct": 82.4,
        "crime_index": 6,
        "nearby_amenities": {
            "grocery_stores": 12,
            "restaurants": 148,
            "parks": 18,
            "schools": 14,
            "hospitals": 4,
            "gyms": 24,
        },
    },
    "97211": {
        "zip_code": "97211",
        "neighborhood": "Alberta Arts District",
        "city": "Portland",
        "state": "OR",
        "report_date": "2025-03-01",
        "walk_score": 89,
        "transit_score": 56,
        "school_rating": 7.4,
        "median_household_income": 78400,
        "population": 24800,
        "median_age": 36.2,
        "yoy_price_change_pct": 1.8,
        "five_year_price_change_pct": 18.4,
        "avg_price_per_sqft": 368,
        "rental_vacancy_rate": 5.1,
        "owner_occupied_pct": 44.1,
        "crime_index": 34,
        "nearby_amenities": {
            "grocery_stores": 10,
            "restaurants": 172,
            "parks": 19,
            "schools": 8,
            "hospitals": 2,
            "gyms": 13,
        },
    },
}

SAMPLE_PROPERTIES = [p for p in PROPERTIES if p["id"] in ("atx-001", "den-002", "mia-003")]


def get_all_properties() -> List[Dict]:
    return PROPERTIES


def get_property_by_id(property_id: str) -> Optional[Dict]:
    for prop in PROPERTIES:
        if prop["id"] == property_id:
            return prop
    return None


def get_price_history(property_id: str) -> Optional[Dict]:
    prop = get_property_by_id(property_id)
    if not prop:
        return None

    if property_id in PRICE_HISTORIES:
        return PRICE_HISTORIES[property_id]

    return {
        "property_id": property_id,
        "address": f"{prop['address']}, {prop['city']}, {prop['state']} {prop['zip_code']}",
        "current_price": prop["price"],
        "original_list_price": prop["price"],
        "history": [
            {
                "date": "2025-02-15",
                "price": prop["price"],
                "event": "Listed",
                "price_change": None,
                "price_change_pct": None,
            }
        ],
        "total_price_changes": 0,
        "days_on_market": prop["days_on_market"],
    }


def search_properties(
    city: Optional[str] = None,
    min_price: Optional[int] = None,
    max_price: Optional[int] = None,
    bedrooms: Optional[int] = None,
    property_type: Optional[str] = None,
) -> List[Dict]:
    results = PROPERTIES

    if city:
        results = [p for p in results if p["city"].lower() == city.lower()]
    if min_price is not None:
        results = [p for p in results if p["price"] >= min_price]
    if max_price is not None:
        results = [p for p in results if p["price"] <= max_price]
    if bedrooms is not None:
        results = [p for p in results if p["bedrooms"] == bedrooms]
    if property_type:
        results = [p for p in results if p["property_type"] == property_type]

    return results


def get_market_stats(city: str) -> Optional[Dict]:
    for key, stats in MARKET_STATS.items():
        if key.lower() == city.lower():
            return stats
    return None


def get_neighborhood_trends(zip_code: str) -> Optional[Dict]:
    return NEIGHBORHOOD_TRENDS.get(zip_code)


def get_sample_properties() -> List[Dict]:
    return SAMPLE_PROPERTIES
